### PR TITLE
Create Ahmad 2016

### PR DESCRIPTION
**Pull request by neowongcilik**
Genome CM

### CODE REVIEW

**Comment by kblin** [comment]
I'm not sure what you are trying to do here.

**Comment by neowongcilik** [comment]
Yupz i want do gene cluster analysis from our genome, but it was so
confusing when entering this github, could you help me please

**Comment by kblin** [comment]
If you want to run antiSMASH on a genome you have, have a look at the antiSMASH website. http://antismash.secondarymetabolites.org/ This repository is a tool to import antiSMASH results into the antiSMASH database (http://antismash-db.secondarymetabolites.org/)

**Comment by kblin** [comment]
Closing the pull request. Feel free to contact us via the contact form on the antiSMASH page http://antismash.secondarymetabolites.org/#!/contact if you have any questions.

**Pull request closed without merging**
